"use client";
import "./app.css";
import { useState } from "react";
import { Bell, Bookmark, Bot, CalendarDays, ChevronDown, ChevronRight, CircleHelp, Database, FileText, Flame, Gauge, Grid2X2, Inbox, LayoutDashboard, Lightbulb, ListFilter, Menu, MoreHorizontal, Plus, Search, Settings, Sparkles, Target, TrendingUp, Users, Workflow, X, Zap } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

type View = "today"|"intelligence"|"competitors"|"inbox"|"ideas"|"production"|"calendar"|"patterns"|"analytics"|"workflows"|"settings";
const nav:[View,string,React.ElementType][] = [["today","今日",LayoutDashboard],["intelligence","情报库",Database],["competitors","对手监控",TrendingUp],["inbox","灵感 Inbox",Inbox],["ideas","选题",Lightbulb],["production","内容执行",FileText],["patterns","Patterns",Grid2X2],["analytics","数据分析",Gauge],["workflows","工作流中心",Workflow],["settings","设置",Settings]];
const content = [
 {title:"AI 让普通人也能做出专业内容",summary:"过去需要专业技能的内容创作，现在通过 AI 工具可以大幅降低门槛。",score:92,tag:"AI 工具",source:"小红书",time:"2 小时前",tone:"blue",image:"#dbe7f5"},
 {title:"短视频的“反套路”内容正在流行",summary:"对于账号中，非教程、非干货的真实记录类内容互动率更高。",score:88,tag:"内容形式",source:"抖音",time:"5 小时前",tone:"purple",image:"#e5ddd5"},
 {title:"独立开发者的增长策略拆解",summary:"一篇关于小而美产品的冷启动策略，值得借鉴到我们的内容选题中。",score:76,tag:"产品增长",source:"B 站",time:"8 小时前",tone:"green",image:"#dce9d9"},
 {title:"Notion + AI：我的内容管理系统",summary:"从收藏到创作，把灵感变成可复用的内容资产。",score:85,tag:"效率",source:"微信公众号",time:"昨天",tone:"orange",image:"#f0e0cc"},
];
const chart=[{d:"周一",v:42},{d:"周二",v:58},{d:"周三",v:49},{d:"周四",v:74},{d:"周五",v:68},{d:"周六",v:92},{d:"周日",v:86}];
const platform=[{name:"抖音",value:56,color:"#3978f6"},{name:"小红书",value:19,color:"#ef5a64"},{name:"B 站",value:12,color:"#8b78e8"},{name:"公众号",value:7,color:"#39b984"}];
function cn(...x:unknown[]){return x.filter(Boolean).map(String).join(" ")}
function Badge({children,tone="blue"}:{children:React.ReactNode,tone?:string}){return <span className={cn("badge",`badge-${tone}`)}>{children}</span>}
function Spark({color="#77a7ff"}:{color?:string}){return <svg width="76" height="32" viewBox="0 0 76 32"><path d="M1 26 L10 20 L18 23 L28 12 L38 18 L49 9 L58 16 L67 4 L75 10" fill="none" stroke={color} strokeWidth="2.5" strokeLinecap="round"/></svg>}
function Stat({icon:Icon,label,value,delta,color="#3378f6",sub}:{icon:React.ElementType,label:string,value:string,delta:string,color?:string,sub:string}){return <div className="stat"><div className="stat-icon" style={{background:`${color}16`,color}}><Icon size={18}/></div><div><div className="eyebrow">{label}</div><div className="stat-value">{value}<span className="up">↗ {delta}</span></div><div className="subtle">{sub}</div></div><Spark color={color}/></div>}
function Shell({view,setView,children}:{view:View,setView:(v:View)=>void,children:React.ReactNode}){const [quick,setQuick]=useState(false);return <div className="shell"><aside className="sidebar"><div className="brand"><div className="brand-mark"><Sparkles size={17}/></div><div>Content Intelligence<br/><span>Workbench</span></div></div><div className="nav">{nav.slice(0,7).map(([id,label,Icon])=><button key={id} onClick={()=>setView(id)} className={cn("nav-item",view===id&&"active")}><Icon size={18}/><span>{label}</span>{id==="inbox"&&<em>12</em>}</button>)}<div className="nav-sep"/>{nav.slice(7).map(([id,label,Icon])=><button key={id} onClick={()=>setView(id)} className={cn("nav-item",view===id&&"active")}><Icon size={18}/><span>{label}</span></button>)}</div><div className="sidebar-note"><Sparkles size={22}/><strong>让好内容<br/>持续发生</strong><p>从观察到创作，用 AI 放大你的内容灵感。</p></div></aside><main className="main"><header className="topbar"><div className="search"><Search size={17}/><span>搜索内容、作者、链接、选题或灵感...</span><kbd>⌘ K</kbd></div><div className="top-actions"><div className="quick-wrap"><button className="quick" onClick={()=>setQuick(!quick)}><Plus size={17}/>快速添加<ChevronDown size={15}/></button>{quick&&<div className="dropdown">{["添加链接","记录灵感","添加对手","新建选题","新建内容"].map(x=><button key={x} onClick={()=>setQuick(false)}><Plus size={15}/>{x}</button>)}</div>}</div><Bell size={19}/><div className="avatar">林</div><ChevronDown size={15}/></div></header><div className="content thin-scroll">{children}</div></main></div>}
function PageHead({eyebrow,title,desc,action}:{eyebrow?:string,title:React.ReactNode,desc:string,action?:React.ReactNode}){return <div className="page-head"><div>{eyebrow&&<div className="eyebrow blue-text">{eyebrow}</div>}<h1>{title}</h1><p>{desc}</p></div>{action}</div>}
function Section({title,action,children,className=""}:{title:string,action?:React.ReactNode,children:React.ReactNode,className?:string}){return <section className={cn("panel",className)}><div className="section-head"><h2>{title}</h2>{action}</div>{children}</section>}
function Today({setView}:{setView:(v:View)=>void}){return <><PageHead title={<>早上好，<br/>让好内容从今天开始 <span className="sparkle">✦</span></>} desc="收集灵感，洞察趋势，借助 AI 生成更好的内容。" action={<div className="date">4月16日　星期二<br/><span>“优秀的创作者，都善于从日常中发现不寻常。”</span></div>}/><div className="stats"><Stat icon={FileText} label="今日收集" value="18" delta="28%" sub="来自对手 11 · 灵感 7"/><Stat icon={Lightbulb} label="待处理灵感" value="24" delta="12%" color="#f1a535" sub="其中 8 条已 AI 分析"/><Stat icon={Target} label="候选选题" value="6" delta="50%" color="#856eea" sub="3 个高优先级"/><Stat icon={Zap} label="已发布内容" value="3" delta="200%" color="#37b986" sub="本周累计"/></div><div className="three-col"><Section title="今日最有价值的洞察" action={<button className="link" onClick={()=>setView("intelligence")}>查看全部 <ChevronRight size={14}/></button>} className="wide"><div className="insights">{content.slice(0,3).map((x,i)=><button className="insight" key={x.title} onClick={()=>setView("intelligence")}><div className="thumb" style={{background:x.image}}><div className="thumb-shape"/></div><div className="insight-copy"><strong>{x.title}</strong><p>{x.summary}</p><Badge tone={x.tone}>{x.tag}</Badge><span className="time">{x.time}</span></div><Bookmark size={16} className="bookmark"/></button>)}</div></Section><Section title="对手动态" action={<button className="link">查看全部 <ChevronRight size={14}/></button>}><div className="activity-list">{["TechFlow","少数派","极客公园","36氪","Notion 中文"].map((x,i)=><div className="activity" key={x}><div className={cn("mini-logo",`logo-${i}`)}>{x[0]}</div><div><strong>{x}</strong><p>{i%2?"发布了视频：新工具上线":"发布了新文章：AI 时代的工作流"}</p></div><span>{i+1} 小时前</span></div>)}</div></Section><Section title="灵感 Inbox" action={<button className="link" onClick={()=>setView("inbox")}>查看全部 <ChevronRight size={14}/></button>}><div className="inbox-preview">{content.map((x,i)=><div className="inbox-row" key={x.title}><div className="tiny-thumb" style={{background:x.image}}/><div><strong>{x.title.slice(0,15)}...</strong><p>{x.source}</p></div><span>{i*2+1} 小时前</span></div>)}</div></Section></div><Section title="AI 推荐" action={<button className="link">换一批 ↻</button>} className="recommend"><div className="recommend-grid"><div className="recommend-list">{["AI 工具 × 个人知识管理：从混乱到清晰的完整指南","短视频时代，深度内容还有机会吗？","独立开发者如何做好内容获客"].map((x,i)=><div className="recommend-item" key={x}><div className="number">{i+1}</div><div><strong>{x}</strong><p>{["基于你最近收藏的内容，匹配度较高","行业话题热度上升，适合抖音 / 视频号","符合你关注的产品增长方向"][i]}</p></div><Badge tone={i===0?"red":"purple"}>{i===0?"高潜力":"适合你"}</Badge><button className="outline" onClick={()=>setView("ideas")}>生成选题 <ChevronRight size={14}/></button></div>)}</div><div className="ai-card"><Sparkles size={25}/><strong>让 AI 成为你的<br/>内容搭档</strong><p>从信息到洞见，从灵感到成稿。</p></div></div></Section></>}

function Intelligence(){const [selected,setSelected]=useState(0); return <><PageHead title="情报库" desc="收集、整理、分析全网优质内容，让每一条内容都成为你的创作灵感。" action={<button className="primary"><Plus size={16}/> 导入内容</button>}/><div className="stats"><Stat icon={FileText} label="今日新增" value="28" delta="40%" sub="较昨日 +8 条"/><Stat icon={Lightbulb} label="待分析" value="56" delta="12%" color="#f1a535" sub="需要 AI 分析的内容"/><Stat icon={Sparkles} label="高潜内容" value="12" delta="300%" color="#856eea" sub="AI 评分 ≥ 80"/><Stat icon={Inbox} label="已归档" value="320" delta="18%" color="#37b986" sub="累计优质内容"/></div><div className="filters"><button>平台　全部平台⌄</button><button>来源　全部来源⌄</button><button>标签　全部标签⌄</button><button>时间　全部时间⌄</button><button>状态　全部状态⌄</button><div className="view-switch"><button className="selected"><ListFilter size={15}/> 列表</button><button>▦ 卡片</button></div></div><div className="intelligence-layout"><Section title={`内容列表　${content.length * 62} 条内容`} action={<button className="select-action">已选择 {selected+1} 项　···</button>} className="table-panel"><div className="table-wrap"><table><thead><tr><th></th><th>内容信息</th><th>平台</th><th>来源</th><th>作者 / 账号</th><th>AI 评分</th><th>状态</th><th>收集时间</th></tr></thead><tbody>{content.concat(content).slice(0,7).map((x,i)=><tr key={i} onClick={()=>setSelected(i%4)} className={selected===i%4?"row-selected":""}><td><input type="checkbox" checked={selected===i%4} readOnly/></td><td><div className="table-content"><div className="tiny-thumb" style={{background:x.image}}/><div><strong>{x.title}</strong><p>{x.summary.slice(0,22)}...</p></div></div></td><td><Badge tone={x.tone}>{x.source}</Badge></td><td><span className="blue-text">{i%2?"对手监控":"手动发现"}</span></td><td>林小北<br/><span className="subtle">@linxiaobei</span></td><td><span className="score">{x.score}</span></td><td><Badge tone={x.score>85?"purple":"orange"}>{x.score>85?"高潜":"待分析"}</Badge></td><td className="subtle">4月16日<br/>10:24</td></tr>)}</tbody></table></div></Section><Detail x={content[selected]}/></div></>}
function Detail({x}:{x:typeof content[0]}){return <aside className="detail"><div className="detail-cover" style={{background:x.image}}><div className="cover-art"><Sparkles size={32}/></div><button className="close"><X size={16}/></button></div><Badge tone="red">AI 高潜内容</Badge><h2>{x.title}</h2><p className="subtle">{x.source} · 4月16日 10:24 收集</p><div className="detail-rule"/><h3>内容洞察</h3><p>过去需要专业技能的内容创作，现在通过 AI 工具可以大幅降低门槛。作者分享了具体的工具、方法和真实经验，具有很强的可操作性。</p><div className="analysis"><div><strong>AI 分析结果</strong><span>92 / 100</span></div>{["选题角度新颖，符合当前热点趋势","内容结构清晰，实用性强","有完整的方法论和案例支撑","受众群体广泛，适合二次创作"].map(x=><p key={x}>✓　{x}</p>)}</div><h3>标签</h3><div className="tag-row"><Badge>AI 工具</Badge><Badge tone="green">生产力</Badge><Badge tone="purple">内容创作</Badge></div><div className="detail-actions"><button className="primary">加入选题</button><button className="outline">标记高潜</button></div></aside>}

const columns=["待筛选","候选选题","待制作","制作中","待发布","已发布"];
function Ideas({setView}:{setView:(v:View)=>void}){const cards=["AI 会取代哪些工作？","普通人如何打造个人品牌？","用 AI 做一份爆款小红书","我用 AI 做内容的真实流程","独立开发者的内容增长","AI 时代，如何保持学习"] ; return <><PageHead title="选题 · 内容执行" desc="从选题到发布，让好内容高效落地。" action={<button className="primary" onClick={()=>setView("calendar")}><Plus size={16}/> 新建选题</button>}/><div className="stats"><Stat icon={FileText} label="今日待做" value="8" delta="20%" sub="包括制作 4 · 剪辑 2 · 发布 2"/><Stat icon={Flame} label="高优先级" value="6" delta="50%" color="#ef6a5d" sub="需要重点跟进"/><Stat icon={CalendarDays} label="本周发布计划" value="12" delta="33%" color="#856eea" sub="较上周 9 条"/><Stat icon={Zap} label="已完成" value="5" delta="150%" color="#37b986" sub="今日已发布 3"/></div><div className="kanban">{columns.map((col,i)=><div className="kanban-col" key={col}><div className="kanban-head"><span className={cn("dot",`dot-${i}`)}/><strong>{col}</strong><small>{i+2}</small></div>{cards.filter((_,j)=>j%6===i|| (i===0&&j===5)).map((title,j)=><button className="idea-card" key={title} onClick={()=>setView("ideas")}><div className="card-menu">···</div><strong>{title}</strong><p>{["这 5 类岗位正在被 AI 重塑...","从 0 到 1 的实操经验分享","从选题到封面，完整流程","亲测好用，附使用场景"][j%4]}</p><div><Badge tone={i===1?"red":i===4?"green":"blue"}>{i===1?"高优先级":i===4?"已排期":"待处理"}</Badge></div><div className="card-foot"><div className="small-avatar">林</div><span>{i%2?"4月18日":"今天 16:00"}</span></div></button>)}<button className="add-column">＋ 添加选题</button></div>)}</div></>}
function Analytics(){return <><PageHead title="内容分析 / 复盘" desc="用数据看见内容的真实效果，找到可复制的增长路径。" action={<button className="filter-date">最近 7 天　⌄　 4月9日 - 4月16日</button>}/><div className="stats five"><Stat icon={FileText} label="总播放量" value="128.6万" delta="42%" sub="较上周 90.5万"/><Stat icon={Sparkles} label="互动率" value="6.8%" delta="1.9%" color="#ef6a7b" sub="较上周 4.9%"/><Stat icon={Zap} label="转化率" value="2.3%" delta="0.8%" color="#f1a535" sub="较上周 1.5%"/><Stat icon={Flame} label="高表现内容" value="12" delta="71%" color="#856eea" sub="播放 > 10万的内容"/><Stat icon={TrendingUp} label="本周增长" value="+38%" delta="" color="#37b986" sub="较上周播放增长"/></div><div className="analytics-grid"><Section title="播放趋势" action={<button className="select-action">播放量⌄</button>}><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart}><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#4a86fa" stopOpacity={.24}/><stop offset="100%" stopColor="#4a86fa" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#edf0f5"/><XAxis dataKey="d" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><Tooltip/><Area type="monotone" dataKey="v" stroke="#3378f6" fill="url(#fill)" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></Section><Section title="平台分布"><div className="pie-wrap"><ResponsiveContainer width="52%" height="100%"><PieChart><Pie data={platform} dataKey="value" innerRadius={50} outerRadius={75} paddingAngle={3}>{platform.map(x=><Cell key={x.name} fill={x.color}/>)}</Pie></PieChart></ResponsiveContainer><div>{platform.map(x=><div className="legend" key={x.name}><i style={{background:x.color}}/>{x.name}<b>{x.value}.3%</b></div>)}</div></div></Section><Section title="AI 复盘结论" className="conclusion"><Badge tone="blue">本周内容整体表现优秀</Badge><p>播放量较上周提升 38%，互动率提升 1.9 个百分点。知识型内容增长明显，3 条内容播放超过 20 万。</p><h3>本周表现亮点</h3>{["AI 工具类内容播放量占比 42%","方法论 + 案例，综合表现更好","晚间 18-22 点发布效果最佳"].map((x,i)=><div className="rank" key={x}><span>{i+1}</span>{x}</div>)}</Section></div><Section title="最近发布的内容" className="recent"><table><thead><tr><th>内容信息</th><th>平台</th><th>发布时间</th><th>播放量</th><th>点赞</th><th>收藏</th><th>AI 表现评分</th></tr></thead><tbody>{content.map((x,i)=><tr key={x.title}><td><div className="table-content"><div className="tiny-thumb" style={{background:x.image}}/><strong>{x.title}</strong></div></td><td>{x.source}</td><td>4月16日 10:24</td><td>{["32.0万","18.6万","12.4万","9.8万"][i]}</td><td>2.1万</td><td>326</td><td><span className="score">{x.score}</span></td></tr>)}</tbody></table></Section></>}

function Generic({view,setView}:{view:View,setView:(v:View)=>void}){const meta:Record<string,[string,string,React.ElementType]>={competitors:["对手监控","实时跟踪竞争对手的内容动态，发现机会，预判趋势。",Users],inbox:["灵感 Inbox","把零散灵感快速收集、分析，变成可执行的内容方向。",Inbox],production:["内容执行","把选题变成内容，让每一步都有清晰进度。",FileText],calendar:["发布日历 / 内容计划","规划、排期、协同，让好内容按时发布。",CalendarDays],patterns:["Patterns","从高表现内容中，提炼可复用的 Hook、结构与表达方式。",Grid2X2],workflows:["工作流中心","连接工具、配置自动化、编排内容生产全流程。",Workflow],settings:["设置","管理工作区、账号连接与偏好设置。",Settings]}; const [title,desc,Icon]=meta[view]||meta.settings; return <><PageHead title={title} desc={desc} action={<button className="primary"><Plus size={16}/> 新建</button>}/><div className="stats"><Stat icon={Icon} label="本周新增" value="42" delta="17%" sub="较上周 +6"/><Stat icon={TrendingUp} label="活跃内容" value="128" delta="23%" color="#856eea" sub="持续增长中"/><Stat icon={Sparkles} label="AI 洞察" value="24" delta="12%" color="#f1a535" sub="等待处理"/><Stat icon={Zap} label="已完成" value="18" delta="40%" color="#37b986" sub="本周累计"/></div><div className="generic-grid"><Section title={view==="workflows"?"内容生产工作流":view==="calendar"?"2024年4月":"工作区概览"} action={<button className="link">查看更多 <ChevronRight size={14}/></button>}><div className="hero-workspace"><div className="hero-icon"><Icon size={28}/></div><h2>{view==="workflows"?"灵感采集 → AI 分析 → 内容发布":view==="calendar"?"本周发布计划":"把你的下一条好内容放在这里"}</h2><p>{view==="workflows"?"所有工具已准备就绪，今天有 5 个自动化任务正在运行。":"从这里开始整理信息、沉淀洞察，并持续输出。"}</p><button className="primary" onClick={()=>setView(view==="inbox"?"intelligence":"ideas")}>开始使用 <ChevronRight size={15}/></button></div></Section><Section title="最近动态"><div className="timeline">{["收藏了一条新链接","AI 完成了 3 条灵感分析","新建了选题","完成内容发布","添加了 5 条灵感到 Inbox"].map((x,i)=><div key={x}><span className={cn("timeline-dot",`dot-${i}`)}/><div><strong>{x}</strong><p>{i%2?"AI 时代的个人知识管理指南":"来自今日工作台的最新活动"}</p></div><time>{i+1} 小时前</time></div>)}</div></Section></div><Section title="推荐行动" className="recommend"><div className="action-grid">{["生成大纲","补全 Hook","生成脚本","素材建议"].map(x=><button key={x} className="action-tile"><Sparkles size={19}/><strong>{x}</strong><p>基于当前内容智能推荐下一步动作</p><ChevronRight size={15}/></button>)}</div></Section></>}

export default function App(){const [view,setView]=useState<View>("today"); const screen=view==="today"?<Today setView={setView}/>:view==="intelligence"?<Intelligence/>:view==="ideas"?<Ideas setView={setView}/>:view==="analytics"?<Analytics/>:<Generic view={view} setView={setView}/>; return <Shell view={view} setView={setView}>{screen}</Shell>}
